name: test
on:
  pull_request:
    paths-ignore:
      - '*.md'
  push:
    branches:
      - master
    paths-ignore:
      - '*.md'
jobs:
  test:
    name: test
    runs-on: ubuntu-latest
    timeout-minutes: 3
    steps:
      - uses: actions/setup-go@v5
        with:
          go-version: 1.22
      - uses: actions/checkout@v4
      - name: Benchmark
        run: go test -bench . -race
      - name: Test (race)
        run: go test -mod vendor ./... -race
      - name: Test (coverage)
        run: go test -mod vendor ./... -coverprofile=coverage.txt -covermode=atomic
      - name: Codecov
        uses: codecov/codecov-action@v5.3.1
        with:
          files: ./coverage.txt
